version: "3"
services:
  web:
    container_name: web
    restart: always
    build: .
    network_mode: host
    ports:
    - "5000:5000"
    depends_on:
    - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    network_mode: host
    volumes:
    - ./data:/data/db
    ports:
    - "27017:27017"